# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Ocean Blog
email: 
description: | # this means to ignore newlines until "baseurl:"
  The official blog for the Ocean project. 

  We keep this record for entirely selfish reasons - we want to be able to
  look back on all we've accomplished with this blog and feel good.

  Feel free to follow along and keep up with what's happening at Ocean!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://oceanhq.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  oceanhq

# Build settings
markdown: kramdown
